image: asapdotid/ansible:tools

mirror:tag:
  stage: deploy
  rules:
    # - if: $CI_COMMIT_TAG != null
    - if: $CI_COMMIT_BRANCH == "develop"
  variables:
    DEPLOY_SSH_HOST_SERVER: $SSH_HOST_SERVER
    DEPLOY_SSH_HOST_PRIVATE_KEY: $SSH_PRIVATE_KEY
    DEPLOY_SSH_HOST_PUBLIC_KEY: $SSH_PUBLIC_KEY
  before_script:
    - ls -al .
    - cat ~/.ssh/id_rsa
  script:
    ## Update GitHub mirror
    - ssh -T git@$SSH_HOST_SERVER || ":" # workaround) force exit code 0
    # Add a new remote location called "mirror"
    - git remote add mirror $GIT_REPOSITORY_URL
    # Discard changes before checking out branch
    - git reset HEAD --hard
    # Push "tags" branch
    - git push mirror --tags
  cache:
    key: $CI_PROJECT_NAME-cache-always
    paths:
      - $CI_PROJECT_NAME.git
