image: asapdotid/alpine:latest

mirror:tag:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG != null
  variables:
    SSH_HOST_TARGET: $SSH_HOST_TARGET
    SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
    SSH_PUBLIC_KEY: $SSH_PUBLIC_KEY
  script:
    ## Update GitHub mirror
    - ssh -T git@$SSH_HOST_TARGET || ":" # workaround) force exit code 0
    # Add a new remote location called "mirror"
    - git remote add mirror $GIT_REPOSITORY_URL
    # Discard changes before checking out branch
    # - git reset HEAD --hard
    # Push "tags" branch
    - git push mirror --tags
  cache:
    key: $CI_PROJECT_NAME-cache-always
    paths:
      - $CI_PROJECT_NAME.git
