image: alpine

mirror:tag:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG != null
  before_script:
    - ./scripts.sh $GH_HOST_SERVER $GH_PRIVATE_KEY $GH_PUBLIC_KEY
  script:
    ## Update GitHub mirror
    - ssh -T git@github.com || ":" # workaround) force exit code 0
    # Add a new remote location called "mirror"
    - git remote add mirror $GH_REPOSITORY_URL
    # Discard changes before checking out branch
    - git reset HEAD --hard
    # Push "tags" branch
    - git push mirror --tags
  cache:
    key: $CI_PROJECT_NAME-cache-always
    paths:
      - $CI_PROJECT_NAME.git
