image: alpine

mirror:tag:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG != null
  before_script:
    # Install prerequisites
    - "command -v ssh-agent >/dev/null || (apk update && apk add openssh-client git bash perl-mime-base64)"
    ## Import SSH key
    # Launch ssh-agent
    - eval $(ssh-agent -s)
    # Add private key from CI variable
    - ssh-add <(echo "$GH_PRIVATE_KEY" | base64 -d)
    # Create ~/.ssh folder if not exist
    - mkdir -p ~/.ssh
    # Restrict the folder privilege
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    ## Update GitHub mirror
    - ssh -T git@github.com || ":" # workaround) force exit code 0
    # Add a new remote location called "mirror"
    - git remote add mirror git@github.com:asapdotid/ansible-role-docker_ce.git
    # Discard changes before checking out branch
    - git reset HEAD --hard
    # Push "main" branch
    - git checkout main && git push mirror --tags
  cache:
    key: $CI_PROJECT_NAME-cache-always
    paths:
      - $CI_PROJECT_NAME.git
