---
# handlers file for docker_ce

- name: Restart docker_ce
  ansible.builtin.service:
    name: "{{ docker_ce_service }}"
    state: restarted
  when:
    - not ansible_check_mode

- name: Apt update cache
  ansible.builtin.apt:
    update_cache: yes
